const tableName = 'transfers';

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
    await knex(tableName).del()
    await knex(tableName).insert([
        {transferId: "1", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 12.23, sourceCurrency: "SGD", targetCurrency:"USD", targetAmount: 9.04},
        {transferId: "2", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 12.23, sourceCurrency: "SGD", targetCurrency:"USD", targetAmount: 9.10},
        {transferId: "3", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 12.23, sourceCurrency: "SGD", targetCurrency:"USD", targetAmount: 8.90},
        {transferId: "4", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 15.50, sourceCurrency: "USD", targetCurrency:"EUR", targetAmount: 14.20},
        {transferId: "5", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 50.00, sourceCurrency: "EUR", targetCurrency:"GBP", targetAmount: 42.75},
        {transferId: "6", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 30.75, sourceCurrency: "GBP", targetCurrency:"AUD", targetAmount: 25.50},
        {transferId: "7", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 45.25, sourceCurrency: "AUD", targetCurrency:"USD", targetAmount: 38.40},
        {transferId: "8", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 22.00, sourceCurrency: "USD", targetCurrency:"EUR", targetAmount: 19.90},
        {transferId: "9", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 38.75, sourceCurrency: "EUR", targetCurrency:"GBP", targetAmount: 33.20},
        {transferId: "10", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 55.60, sourceCurrency: "GBP", targetCurrency:"AUD", targetAmount: 48.30},
        {transferId: "11", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 18.00, sourceCurrency: "AUD", targetCurrency:"USD", targetAmount: 15.75},
        {transferId: "12", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 29.50, sourceCurrency: "USD", targetCurrency:"EUR", targetAmount: 26.80},
        {transferId: "13", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 62.75, sourceCurrency: "EUR", targetCurrency:"GBP", targetAmount: 55.45},
        {transferId: "14", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 35.20, sourceCurrency: "GBP", targetCurrency:"AUD", targetAmount: 31.10},
        {transferId: "15", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 42.30, sourceCurrency: "AUD", targetCurrency:"USD", targetAmount: 36.90},
        {transferId: "16", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 19.90, sourceCurrency: "USD", targetCurrency:"EUR", targetAmount: 17.30},
        {transferId: "17", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 33.50, sourceCurrency: "USD", targetCurrency:"EUR", targetAmount: 29.80},
        {transferId: "18", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 28.75, sourceCurrency: "EUR", targetCurrency:"GBP", targetAmount: 24.60},
        {transferId: "19", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 42.00, sourceCurrency: "GBP", targetCurrency:"AUD", targetAmount: 36.90},
        {transferId: "20", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 15.25, sourceCurrency: "AUD", targetCurrency:"USD", targetAmount: 13.50},
        {transferId: "21", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 27.00, sourceCurrency: "USD", targetCurrency:"EUR", targetAmount: 23.90},
        {transferId: "22", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 31.80, sourceCurrency: "EUR", targetCurrency:"GBP", targetAmount: 27.50},
        {transferId: "23", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 48.50, sourceCurrency: "GBP", targetCurrency:"AUD", targetAmount: 42.20},
        {transferId: "24", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 17.20, sourceCurrency: "AUD", targetCurrency:"USD", targetAmount: 15.25},
        {transferId: "25", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 22.00, sourceCurrency: "USD", targetCurrency:"EUR", targetAmount: 19.70},
        {transferId: "26", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 39.25, sourceCurrency: "EUR", targetCurrency:"GBP", targetAmount: 34.80},
        {transferId: "27", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 54.60, sourceCurrency: "GBP", targetCurrency:"AUD", targetAmount: 47.80},
        {transferId: "28", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 13.80, sourceCurrency: "AUD", targetCurrency:"USD", targetAmount: 12.25},
        {transferId: "29", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 25.00, sourceCurrency: "USD", targetCurrency:"EUR", targetAmount: 22.40},
        {transferId: "30", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 47.50, sourceCurrency: "EUR", targetCurrency:"GBP", targetAmount: 41.80},
        {transferId: "31", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 36.20, sourceCurrency: "GBP", targetCurrency:"AUD", targetAmount: 31.70},
        {transferId: "32", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 19.00, sourceCurrency: "AUD", targetCurrency:"USD", targetAmount: 16.80},
        {transferId: "33", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 29.50, sourceCurrency: "USD", targetCurrency:"EUR", targetAmount: 26.10},
        {transferId: "34", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 44.80, sourceCurrency: "EUR", targetCurrency:"GBP", targetAmount: 39.50},
        {transferId: "35", paymentMode: "Bank Transfer", paymentReference: "forex",
            sourceAmount: 52.30, sourceCurrency: "GBP", targetCurrency:"AUD", targetAmount: 45.90},
        {transferId: "36", paymentMode: "Credit Card", paymentReference: "forex",
            sourceAmount: 11.70, sourceCurrency: "AUD", targetCurrency:"USD", targetAmount: 10.35},
    ]);
};
